services:
  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}
    volumes:
      - ./migrations:/migrations:ro
    command: [ "migrate", "run", "--source", "/migrations" ]
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pocketpair-net
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}
      RUST_LOG: ${RUST_LOG:-info}
      PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      migrator:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - pocketpair-net
      - infra

networks:
  pocketpair-net:
    driver: bridge
  infra:
    external: true

#volumes:
#  pg_data: